# Generated by Django 5.1.2 on 2024-10-20 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carriers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrier',
            old_name='patent',
            new_name='dni',
        ),
        migrations.AddField(
            model_name='carrier',
            name='email',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrier',
            name='phone',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('patent', models.CharField(max_length=100)),
                ('id_carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('price', models.FloatField()),
                ('service_station', models.CharField(max_length=100)),
                ('id_paten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carriers.patent')),
            ],
        ),
    ]
